# Generated by Django 5.2.1 on 2025-05-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileupload", "0003_document_uploaded_at_alter_document_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
